AWSTemplateFormatVersion: 2010-09-09
Description: >-
  root-access-aws

Transform:
- AWS::Serverless-2016-10-31

Resources:  
  SNSNylasMessage:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that handles the delivery of a new Nylas message.
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: src/handlers/sns-nylas-message.snsNylasMessageHandler
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:630351220487:nylas-streams
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - RootAccessLambdaExecutionRole
        - AmazonSNSReadOnlyAccess

Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT_PREFIX: ''
